-- Active: 1662196093279@@127.0.0.1@3306@db

DROP TABLE IF EXISTS Order_Item;

DROP TABLE IF EXISTS Delivery;

DROP TABLE IF EXISTS db.Order;

DROP TABLE IF EXISTS Driver;

DROP TABLE IF EXISTS Coupon_R;

DROP TABLE IF EXISTS C_Batch_Customer;

DROP TABLE IF EXISTS Coupon_Batch;

DROP TABLE IF EXISTS Distribution_Rule;

DROP TABLE IF EXISTS Coupon_Item;

DROP TABLE IF EXISTS Coupon;

DROP TABLE IF EXISTS Menu_Item;

DROP TABLE IF EXISTS Customer;

DROP TABLE IF EXISTS Restaurant_RCategory;

DROP TABLE IF EXISTS RCategory;

DROP TABLE IF EXISTS Request;

DROP TABLE IF EXISTS AppStaff;

DROP TABLE IF EXISTS Staff;

DROP TABLE IF EXISTS PrivilegeLists;

DROP TABLE IF EXISTS Restaurant;

DROP TABLE IF EXISTS User;
